###login 
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "name":"Suman",
    "email":"roka7362@gmail.com",
    "password":"123456789",
    "role":"admin"
}

###login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
   "email":"roka7362@gmail.com",
    "password":"123456789" 
}

###verify the email
POST http://localhost:4000/api/auth/verify-email
Content-Type: application/json

{
    "email":"roka7362@gmail.com",
    "code":"871246"
}

###getMe 
GET http://localhost:4000/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDkxYWQ5NWEyMjlkYjZlZDg4MzYyNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3OTcwOTE4OSwiZXhwIjoxNzgwMzEzOTg5fQ.80oV2zp5Oba7Wz-IQdGDHP0pOAhLklRs7ure1m9Vjv8


###get userprofle 
GET http://localhost:4000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDkxYWQ5NWEyMjlkYjZlZDg4MzYyNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3OTcwOTE4OSwiZXhwIjoxNzgwMzEzOTg5fQ.80oV2zp5Oba7Wz-IQdGDHP0pOAhLklRs7ure1m9Vjv8


###get public profile
GET http://localhost:4000/api/user/public/6a091ad95a229db6ed883624